export const GET_TEMPLATES = 'GET_TEMPLATES';
export const SET_TEMPLATES = 'SET_TEMPLATES';
export const SET_CURRENT_TEMPLATE = 'SET_CURRENT_TEMPLATE';
export const IS_LOADED = 'IS_LOADED';
export const FONT_CHANGER_TOGGLE = 'FONT_CHANGER_TOGGLE';
export const UPDATE_CURRENT_TEMPLATE = 'UPDATE_CURRENT_TEMPLATE';